config/routes.rb
Rails.application.routes.draw do
  resources :videos

  # resources :courses

  resources :courses do
	 	
	 	
	 	get :enroll
	  collection do
	    get :tag
	    
	  end
	end

  
  root to: 'visitors#index'
  devise_for :users
  resources :users
	
  get 'courses/canvas/list', to: 'courses#list_canvas_courses'
  get 'courses/import/:id', to: 'courses#import'
  # get 'courses/enroll/:id', to: 'courses#enroll'
  #


end

app/models/course.rb
class Course < ActiveRecord::Base
  acts_as_taggable # Alias for acts_as_taggable_on :tags
  acts_as_taggable_on :skills, :interests
  has_many :videos

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable

  devise :cas_authenticatable, :registerable

  def cas_extra_attributes=(extra_attributes)
    extra_attributes.each do |name, value|
      case name.to_sym
      when :fullname
        self.fullname = value
      when :email
        self.email = value
      end
    end
  end
end

app/models/video.rb
class Video < ActiveRecord::Base
	belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
Canvas.client.token = 'RM14FSnQXEoDW9J03IWh1n1hKPbs6nH5PSXgMXzatzwOGAasbTFtqW5MzOsG6fOT'
Canvas.client.url = 'http://192.168.1.115:3000'

class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def tag_cloud
    @tags = Course.tag_counts_on(:tags)
    # logger.debug @tags
  end

  def tag
    @courses = Course.tagged_with(params[:id])
    @tags = Course.tag_counts_on(:tags)
    render :action => 'index'
  end
  
  def index
    @tags = Course.tag_counts_on(:tags)
    logger.debug @tags

    @courses = Course.all
    respond_with(@courses)
  end

  def show
    @tags = @course.tag_counts_on(:tags)
    id = params[:id]
    # url  = format "courses/%d/users?enrollment_type=teacher", @course.canvas_id
    url  = format "courses/%d/users", @course.canvas_id
    # logger.debug "url: #{url}" 
    
    @teachers = Canvas.client.get url ,enrollment_type: 'teacher'
    @students = Canvas.client.get url ,enrollment_type: 'student'

    @joined = false;
    logger.debug @students
    @students.each do |student|
      url = format "users/%d/profile" ,student['id']
      logger.debug "url: #{url}" 
      @profile= Canvas.client.get url 
      logger.debug current_user.username + @profile['login_id']
      if current_user.username ===  @profile['login_id']
        # if current_user.canvas_user_id ==0
        #   @user = User.find(current_user.id)
        #   @user.canvas_user_id = student['id']
        #   @user.save()
        # end
        logger.debug @profile
        @joined = true
      end  
    end

    
    @teachers.each do |teacher|
      url = format "users/%d/profile" ,teacher['id']
      @profile= Canvas.client.get url 
      # logger.debug @profile
      teacher['avatar_url'] = @profile['avatar_url'];
      # if current_user.canvas_user_id ===nil
      #   if current_user.username ===  @profile['login_id']
      #     @user = User.find(current_user.id)
      #     @user.canvas_user_id = student['id']
      #     @user.save()
      #   end            
      # end
    end

    # logger.debug "teachers: #{@teachers}" 
    
        
    respond_with(@course,@techers,@students,@joined)
  end

  def new
    @course = Course.new
    respond_with(@course)
  end

  def edit

    # @videos = Video.all
    
  end

  def create
    @course = Course.new(course_params)
    @course.save
    respond_with(@course)
  end

  def update
    @course.update(course_params)
    respond_with(@course)
  end

  def destroy
    @course.destroy
    respond_with(@course)
  end

  def list_canvas_courses
    @courses_canvas = Canvas.client.get 'courses'
    logger.debug "courses: #{@courses_canvas}" 
    @courses = []
    @courses_canvas.each do |course|
      if( true === is_imported(course["id"]))
      else
        # logger.debug format("have not imported:%d" , course["id"])
        @courses << course
      end
    end
    respond_with(@courses)
  end

  def import
    id = params[:id]
    url = format "courses/%d", id 
    
    logger.debug "url: #{url}" 
    
    @courses = Canvas.client.get url
    @canvas_course = @courses
    logger.debug "courses: #{@canvas_course}" 
    @course = Course.new
    @course.canvas_id = @canvas_course["id"]
    @course.name = @canvas_course["name"]
    @course.start_at = @canvas_course["start_at"]
    @course.end_at = @canvas_course["end_at"]
    @course.save
  end



  def enroll
    # id = params[:id]
    # @course = Course.find(params[:id])
    @course = Course.find(params[:course_id])
    url  = format "courses/%d/enrollments", @course.canvas_id
    logger.debug "url" +url
    user_id = current_user.canvas_user_id
    preload = { user_id: user_id ,
                type: 'StudentEnrollment',
                enrollment_state: 'active',
                # course_section_id: 1,
                limit_privileges_to_course_section: true,
                notify:false
              }
    logger.debug preload
                                       
    Canvas.client.post url, enrollment: preload


  end  

 

  private 

  def is_imported(id)
     @where = "canvas_id="+format("%d", id)
     # logger.debug @where
     @course = Course.where(:canvas_id => id).first

    if @course != nil 
      # logger.debug @course
      logger.debug format("is imported:%d" , id)
      return true
    else
      return false
    end
  end


  private
    def set_course
      @course = Course.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:name, :tag_list, :description, :cover_image_url, :start_at, :end_at, :score, :difficulty, :price, :duration, :type, :peoples, :canvas_id)
    end
end

app/controllers/users_controller.rb
Canvas.client.token = 'RM14FSnQXEoDW9J03IWh1n1hKPbs6nH5PSXgMXzatzwOGAasbTFtqW5MzOsG6fOT'
Canvas.client.url = 'http://192.168.1.115:3000'
# Canvas.client.account = '200'

class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @courses = Canvas.client.get 'courses'
    logger.debug "courses: #{@courses}" 
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @videos = Video.all
    respond_with(@videos)
  end

  def show
    respond_with(@video)
  end

  def new
    @video = Video.new
    respond_with(@video)
  end

  def edit
    @course = Course.all
  end

  def create
    @video = Video.new(video_params)
    @video.save
    respond_with(@video)
  end

  def update
    @video.update(video_params)
    respond_with(@video)
  end

  def destroy
    @video.destroy
    respond_with(@video)
  end

  private
    def set_video
      @video = Video.find(params[:id])
    end

    def video_params
      params.require(:video).permit(:name, :course_id, :url, :description, :create_at, :duration, :format)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
	include ActsAsTaggableOn::TagsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/courses/_course.html.erb
	<div class="col-xs-4">
	    	<div class="courseBox">
			<p><%= link_to image_tag(course.cover_image_url), course %></p>
			<p class="title"><%= link_to course.name, course %></p>
			<div class="row" style="margin:0;">
				<div class="col-xs-6" style="text-align:left;"><p class="content">2014-8-02</p></div>
				<div class="col-xs-6" style="text-align:right;"><p class="content"><span class="glyphicon glyphicon-user"></span> 27168</p></div>
			</div>
		</div>
	</div>

app/views/courses/_form.html.erb
<%= simple_form_for(@course) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :cover_image_url %>
    <%= f.input :start_at %>
    <%= f.input :end_at %>
    <%= f.input :score %>
    <%= f.input :difficulty %>
    <%= f.input :price %>
    <%= f.input :duration %>
    <%= f.input :type %>
    <%= f.input :peoples %>
    <%= f.input :canvas_id %>
    <%= f.label :tag_list %>
    <%= f.text_field :tag_list %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>

  <% @course.videos.each do |video| %>
    <%= link_to video.name, video_path(video) %>
    </li>
  <% end %>



<% end %>

<div id="wrapper">

    <div class="video-holder">
        <video id="video" class="video-js vjs-default-skin"
               controls preload="auto" width="800" height=600
               data-setup=''
               poster="">
        </video>
        <div class="playlist-components">
            <div class="playlist">
                <ul></ul>
            </div>
            <div class="button-holder">
                <img id="prev" alt="Previous video" src="img/Previous.png">
                <img id="next" alt="Next video" src="img/Next.png">
            </div>
        </div>
    </div>
    <div class="panels centered">
        <pre></pre>
    </div>
     <script>
  var videos = [
      <% @course.videos.each do |video| %>
      {
      src : [
        '<%= video.url %>',
      ],
      poster : 'http://flowplayer.org/media/img/demos/minimalist.jpg',
      title : '<%= video.name %>'
    },
      <% end %>

  ];
  </script>
</div>
   
  </body>

  <script src="https://rawgithub.com/Belelros/videojs-playLists/master/lib/videojs-playlists.js" data-cover></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="/videojs-playLists/example/main.js"></script>

app/views/courses/edit.html.erb
<h1>Editing course</h1>
    <link href="http://belelros.github.io/videojs-playLists/css/main.css" rel="stylesheet">
    <script src="http://vjs.zencdn.net/4.0/video.js"></script>
<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/enroll.html.erb
<h1>New course</h1>


<%= link_to 'Back', courses_path %>

app/views/courses/enroll_course.html.erb
<h1>New course</h1>


<%= link_to 'Back', courses_path %>

app/views/courses/import.html.erb
<h1>New course</h1>


<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<link href="/bundles/renaissanceweb/css/plaza.css" rel="stylesheet" type="text/css">
</link>
<h1>Listing courses</h1>

<% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
  <%= link_to tag.name, { :action => :tag, :id => tag.name }, :class => css_class %>
<% end %>

<div class="col-xs-9">
<div class="row plazaPanel plazaPanel-center">
<div class="col-xs-12">
<p style="color: #b01e00;font-size: 30px;margin: 15px;">课程分类&gt;全部</p>
<div id="courses" style="overflow:hidden">

<div class="row" style="opacity:0.1;">
 <% @courses.each do |course_row| %>
   <%= render course_row %>
          
 <% end %>
</div>
    <script type="text/javascript">
  $(function(){
    $(".row").transit({
      opacity:1
    },500);
  });
</script>

</div>
</div>
</div>
</div>
<br>

<%= link_to 'New Course', new_course_path %>
<%= link_to 'Import Canvas Course', courses_canvas_list_path %>

<script src="/bundles/renaissanceweb/js/plazaNavi.js"></script>
<script src="/bundles/renaissanceweb/js/pageAjax.js"></script>
<script src="/bundles/renaissanceweb/js/plazaPage.js"></script>

app/views/courses/list_canvas_courses.html.erb
<h1>Listing courses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start at</th>
      <th>End at</th>
      <th>Canvas ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>

        <td><%= course["name"] %></td>
        <td><%= course["start_at"] %></td>
        <td><%= course["end_at"] %></td>
        <td><%= course["id"] %></td>
        <td><%= link_to 'import', "/courses/import/#{course["id"]}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<link href="/bundles/renaissanceweb/css/star-rating.min.css" rel="stylesheet" type="text/css"></link>
<link href="/bundles/renaissanceweb/css/1.0/common.css" rel="stylesheet" type="text/css"></link>


<p id="notice"><%= notice %></p>
<% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
  <%= link_to tag.name, { :action => :tag, :id => tag.name }, :class => css_class %>
<% end %>



|
<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>



<style type="text/css">
.timeLine > .item:hover{
  border-bottom:3px dashed #B01E00;
}

</style>
<div class="container-fluid">
<!-- 课程介绍 -->
<div class="col-md-10 col-md-offset-1 courseProfile whiteRec">
<div class="col-md-12" >
<ol class="breadcrumb courseBC">
<li><a href="#">课程分类</a></li>
<li><a href="#">Web前端开发技术</a></li>
</ol>
</div>
<div class="col-md-12 profileMain" style="">
<div class="col-md-4 profileBase">
<div class="col-md-12" >
<div class="
cPrice dashedRec">
<p class="title">
<i class="fa fa-money"></i> 售价
</p>
<p class="content">
<%= @course.price %>
</p>
</div>
<div class=" cStars dashedRec">
<p class="title">
<i class="fa fa-star"></i> 评价
</p>
<p class="content">
<%= @course.score %>星
</p>
</div>
<div class="cMembers dashedRec">
<p class="title">
<i class="fa fa-users"></i> 报名
</p>
<p class="content">
<%= @course.peoples %>人
</p>
</div>
</div>
<div class="col-md-12">
<% if @joined===false %>

  <%= link_to '加入', course_enroll_path(@course), :class => "button button-large button-flat-flame" %>
<% else %>
  <%= link_to '开始学习', "http://192.168.1.115:3000/courses/#{@course.canvas_id}" , :class => "button button-large button-flat-flame" %>
<% end %>
</div>
</div>
<% if @course.videos.length >0 %>
<div class="col-md-8 profileImg">
<%= videojs_rails sources: { mp4: "#{@course.videos.first.url}", webm: "#{@course.videos.first.url}"}, width:"800" do %>
    Please enable <b>JavaScript</b> to see this content.
<%- end %>
</div>
<% else %>
<div class="col-md-8 profileImg">
<img src="<%= @course.cover_image_url %>">
</div>
<% end %>
<div class="col-md-4 profileInfo">
<div class="col-md-12">
<p class="courseName"><%= @course.name %></p>
<p class="courseCon"><%= @course.description %></p>
</div>
</div>
</div>
<div class="col-md-12 profileDetail">
<div class="col-md-8 profileLPanel">
<div class="navbarMin">
<ul class="clearfix">
<li><a class="active">课时</a></li>
<li><a>证书</a></li>
<li><a>笔记</a></li>
<li><a>讨论</a></li>
<li><a>证书</a></li>
</ul>
</div>
<div class="navCon col-md-12">
<!-- 左侧框内容 -->


</div>
</div>
<div class="col-md-4 profileRPanel">
<div class="col-md-12 profileTeacher">
<p class="title">授课老师</p>
<% @teachers.each do |teacher| %>

<div class="col-md-12 info">
    <div class="col-md-5"><img class="headPic img-circle" src="<%= teacher['avatar_url'] %>"/></div>
<div class="col-md-7">
<p class="name">
   <%= teacher['short_name'] %>
</p>
 
<p class="property">
Web前端工程师
</p>
</div>

</div>
<% end %>
</div>
<div class="col-md-12 profileComments">
<p class="title">我要评价:<input id="makeStars" type="number" ></p>
<p>
</p>
<p class="inputComm"><textarea></textarea><a class="button button-large button-flat-flame">提交</a></p>
<p class="title">
最新评价
</p>
<div class="commList">
<ul>
<li class="clearfix">
<div class="col-md-2 headPic "><img class="img-circle" src="/bundles/renaissanceweb/img/commHead.jpg"></div>
<div class="col-md-8 detail">
<p>
<span class="name">田馥甄</span>
<span class="stars">
<i class="fa fa-star"></i>
</span>
</p>
<p class="content">Tim老师讲的非常不错</p>
</div>
<div class="col-md-2 time">2小时前</div>
</li>
<li class="clearfix">
<div class="col-md-2 headPic "><img class="img-circle" src="/bundles/renaissanceweb/img/commHead.jpg"></div>
<div class="col-md-8 detail">
<p>
<span class="name">王尧山</span>
<span class="stars">
<i class="fa fa-star"></i>
<i class="fa fa-star"></i>
<i class="fa fa-star"></i>
</span>
</p>
<p class="content">非常不错</p>
</div>
<div class="col-md-2 time">12小时前</div>
</li>
</ul>
</div>
</div>
</div>
</div>
</div>
<!-- 相关课程 -->
<div class="col-md-10 col-md-offset-1 courseRec whiteRec">
<div class="col-md-12" style="font-size:2.5rem;padding-bottom:10px;">
相关课程
</div>
<div class="col-md-3 courseRecCard">
<div class="view viewForCard">
<img src="/bundles/renaissanceweb/img/相关课程jQuery.png">
<div class="mask">
<h2>jQuery</h2>
<p>Jquery是继prototype之后又一个优秀的Javascript框架。它是轻量级的js库 ，它兼容CSS3，还兼容各种浏览器.jQuery使用户能更方便地处理HTML</p>
<a href="#" class="info"><i class="fa fa-hand-o-right"></i></a>
</div>
<div class="info"><p class="title">jQuery设计</p><p class="members"><i class="fa fa-user"></i> 30人</p></div>
</div>
</div>
<div class="col-md-3 courseRecCard">
<div class="view viewForCard">
<img src="/bundles/renaissanceweb/img/相关课程jQuery.png">
<div class="mask">
<h2>jQuery</h2>
<p>Jquery是继prototype之后又一个优秀的Javascript框架。它是轻量级的js库 ，它兼容CSS3，还兼容各种浏览器.jQuery使用户能更方便地处理HTML</p>
<a href="#" class="info"><i class="fa fa-hand-o-right"></i></a>
</div>
<div class="info"><p class="title">jQuery设计</p><p class="members"><i class="fa fa-user"></i> 30人</p></div>
</div>
</div>
<div class="col-md-3 courseRecCard">
<div class="view viewForCard">
<img src="/bundles/renaissanceweb/img/相关课程jQuery.png">
<div class="mask">
<h2>jQuery</h2>
<p>Jquery是继prototype之后又一个优秀的Javascript框架。它是轻量级的js库 ，它兼容CSS3，还兼容各种浏览器.jQuery使用户能更方便地处理HTML</p>
<a href="#" class="info"><i class="fa fa-hand-o-right"></i></a>
</div>
<div class="info"><p class="title">jQuery设计</p><p class="members"><i class="fa fa-user"></i> 30人</p></div>
</div>
</div>
<div class="col-md-3 courseRecCard">
<div class="view viewForCard">
<img src="/bundles/renaissanceweb/img/相关课程jQuery.png">
<div class="mask">
<h2>jQuery</h2>
<p>Jquery是继prototype之后又一个优秀的Javascript框架。它是轻量级的js库 ，它兼容CSS3，还兼容各种浏览器.jQuery使用户能更方便地处理HTML</p>
<a href="#" class="info"><i class="fa fa-hand-o-right"></i></a>
</div>
<div class="info"><p class="title">jQuery设计</p><p class="members"><i class="fa fa-user"></i> 30人</p></div>
</div>
</div>
</div>
<div class="col-md-1 rightControls">
<ul>
<li class="">
<a><i class="fa fa-user" title="进入个人中心"></i></a>
</li>
<li class="">
<a><i class="fa fa-qrcode" title="扫描二维码"></i></a>
</li>
<!-- 返回顶部 -->
<li class="toTop">
<a><i class="fa fa-angle-up" title="返回顶部"></i></a>
</li>
</ul>
</div>
</div>

<script src="/bundles/renaissanceweb/js/star-rating.min.js "></script>
<script src="/bundles/renaissanceweb/js/courseIntro.js"></script>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>


<!-- navbar -->
<nav class="navbar navbar-default custom" role="navigation" style="background-image:url(/bundles/renaissanceweb/img/2nd/navi_bg.png);border-bottom: 4px #92a4a4 dashed;">
<div class="container-fluid">
  <div class="navbar-header" style="margin-left:5%">
    <img src="/bundles/renaissanceweb/img/2nd/navi_logo.png">
  </div>

  <div class="collapse navbar-collapse" style="margin-right:5%">
    <ul id="formul" class="nav navbar-nav navbar-right" style="padding-top:40px;">
      <% if user_signed_in? %>
        <li style="color:#ffffff;font-size: 22px;font-weight: 700;"><%= current_user.username %>(<%= current_user.id %>)</li>
      <% else %>

        <li id="toReg"><a href="/register" style="color:#ffffff;font-size: 22px;font-weight: 700;">注册</a></li>
        <li id="toLogin1"><%= link_to '登录', new_user_session_path %> </li>
      <% end %>
    </ul>
  </div>
  <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
</div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'Home', root_path, class: 'navbar-brand' %></li>
<li><%= link_to 'About', page_path('about') %></li>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  
  <li><%= link_to 'Courses', courses_path %></li>
  <li><%= link_to 'Videos', videos_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Renaissance" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Renaissance" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <script src="/bundles/renaissanceweb/js/jquery-1.11.1.min.js"></script>
<script src="/bundles/renaissanceweb/js/jquery.transit.js"></script>
<script src="/bundles/renaissanceweb/lib/bootstrap/js/bootstrap.js"></script>
<script src="/bundles/renaissanceweb/js/base.js"></script>

<link href="/bundles/renaissanceweb/lib/bootstrap/css/bootstrap.min.css" type="text/css" rel="stylesheet"></link>

<link href="/bundles/renaissanceweb/lib/font-awesome-4.1.0/css/font-awesome.min.css" type="text/css" rel="stylesheet"></link>

    <link href="/bundles/renaissanceweb/css/1.0/frontpage.css" rel="stylesheet" type="text/css">
    <link href="/bundles/renaissanceweb/css/buttons.css" rel="stylesheet" type="text/css">

    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="bodyWrapper">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/users/_course.html.erb
<td><%= link_to course.course_code, course %></td>

app/views/users/_user.html.erb
<td><%= link_to user.username, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>

        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Email: <%= @user.username if @user.username %></p>

app/views/videos/_form.html.erb
<%= simple_form_for(@video) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <% if @course !=nil %>
    <%= f.select :course_id, @course.collect{|c|[ c.name, c.id ]}.unshift(["请选择一个Course", 0]), :class => 'xxx' %>  
    <% end %>
    <%= f.input :url %>
    <%= f.input :description %>
    <%= f.input :create_at %>
    <%= f.input :duration %>
    <%= f.input :format %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<h1>Listing videos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Course</th>
      <th>Description</th>
      <th>Create at</th>
      <th>Duration</th>
      <th>Format</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.name %></td>
        <% if video.course != nil %>
        <td><%= video.course.name %></td>
        <% else %>
        <td></td>
        <% end %>
        <td><%= video.description %></td>
        <td><%= video.create_at %></td>
        <td><%= video.duration %></td>
        <td><%= video.format %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @video.name %>
</p>

<p>
  <strong>Course:</strong>
  <%= @video.course_id %>
</p>


<p>
  <strong>Description:</strong>
  <%= @video.description %>
</p>

<p>
  <strong>Create at:</strong>
  <%= @video.create_at %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @video.duration %>
</p>

<p>
  <strong>Format:</strong>
  <%= @video.format %>
</p>

<%= videojs_rails sources: { mp4: "#{@video.url}"}, width:"800" do %>
    Please enable <b>JavaScript</b> to see this content.
<%- end %>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>